---
- name: Downloding Pip install script
  get_url:
    url=https://bootstrap.pypa.io/get-pip.py
    dest=vendor/pip/get-pip.py

- name: Installing Pip
  become: yes
  command: python vendor/pip/get-pip.py creates=/usr/local/bin/pip

- name: Installing Pip modules
  pip: name={{ item }} extra_args='--user'
  with_items: pipinstalls
