set nocompatible                                            " Don't bother with Vi compatibility
syntax enable                                               " Enable syntax highlighting

" Configure Vundle
filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
if filereadable(expand("~/.vundlefile"))
  source ~/.vim/.vundlefile
endif

call vundle#end()
filetype plugin indent on

set autoindent
set autoread                                                " Reload files when changed on disk
set list                                                    " Show trailing whitespaces
set listchars=tab:▸\ ,trail:▫
set number                                                  " Show line number
set ruler                                                   " Show where you are