set nocompatible                                        " Don't bother with Vi compatibility
syntax enable                                           " Enable syntax highlighting

" Configure Vundle
filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
if filereadable(expand("~/.vundlefile"))
  source ~/.vim/.vundlefile
endif

call vundle#end()
filetype plugin indent on

set autoindent
set autoread                                            " Reload files when changed on disk
set backspace=2                                         " Fix broken backspace in some setups
set backupcopy=yes
set backupdir=~/.vim/tmp/backup//                       " Don't populate working directory with backups
set directory=~/.vim/swap//                             " Don't populate working directory with swaps
set encoding=utf-8
set expandtab                                           " Expand tabs to spaces
set ignorecase                                          " Case-insensitive search
set incsearch                                           " Search as you type
set laststatus=2                                        " Always show status line
set list                                                " Show trailing whitespaces
set listchars=tab:▸\ ,trail:▫
set nowrap                                              " Do not wrap long lines
set number                                              " Show line number
set ruler                                               " Show where you are
set scrolloff=3                                         " SHow context above/below cursorline
set shiftwidth=2                                        " Normal mode indentation commands uses 2 spaces
set showcmd                                             " Show info for the current command
set smartcase                                           " Case-sensitive search if any caps
set softtabstop=2                                       " Insert mode tab and BS uses 2 spaces
set synmaxcol=200                                       " Turn off syntax highlighting for long lines
set tabstop=8                                           " Actual tabs occupy 8 characters
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                            " show a navigable menu for tab completion
set wildmode=longest,list,full

" Keyboard Remaps
inoremap jj <ESC>

" Load local .vimrc file if it exists
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif