set nocompatible                                        " Don't bother with Vi compatibility
syntax enable                                           " Enable syntax highlighting

" Configure Vundle
filetype on
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
if filereadable(expand("~/.vim/vundlefile"))
  source ~/.vim/vundlefile
endif

call vundle#end()
filetype plugin indent on

set autoindent
set autoread                                            " Reload files when changed on disk
set background=dark
set backspace=2                                         " Fix broken backspace in some setups
set backupcopy=yes
set backupdir=$HOME/.vim/tmp/backup//                   " Don't populate working directory with backups
set directory=$HOME/.vim/tmp/swap//                     " Don't populate working directory with swaps
set encoding=utf-8
set expandtab                                           " Expand tabs to spaces
set ignorecase                                          " Case-insensitive search
set incsearch                                           " Search as you type
set hidden                                              " Opening new files in buffer hides the current file
set laststatus=2                                        " Always show status line
set list                                                " Show trailing whitespaces
set listchars=tab:▸\ ,trail:▫
set nowrap                                              " Do not wrap long lines
set number                                              " Show line number
set ruler                                               " Show where you are
set scrolloff=3                                         " SHow context above/below cursorline
set shiftwidth=2                                        " Normal mode indentation commands uses 2 spaces
set showcmd                                             " Show info for the current command
set smartcase                                           " Case-sensitive search if any caps
set softtabstop=2                                       " Insert mode tab and BS uses 2 spaces
set synmaxcol=200                                       " Turn off syntax highlighting for long lines
set textwidth=0                                         " Do not physically add line breaks
set tabstop=8                                           " Actual tabs occupy 8 characters
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                            " show a navigable menu for tab completion
set wildmode=longest,list,full

silent! colorscheme solarized

" Keyboard Remaps
let mapleader = ','
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
inoremap jj <ESC>
nnoremap <leader>a :Ack<space>
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>] :TagbarToggle<CR>
noremap <silent> <leader>V :source $MYVIMRC<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Plugin Configurations
if executable('ag')
  let g:ackprg = 'ag --nogroup --nocolor --column --smart-case'
endif

silent! python from powerline.vim import setup as powerline_setup
silent! python powerline_setup()
silent! python del powerline_setup

" Load local .vimrc file if it exists
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
