---
- name: Initializing Vim Bundle
  command: vim +PluginInstall! +PluginClean +qall

- name: Configuring Command-T
  command:
    ruby extconf.rb
    creates=~/.vim/bundle/command-t/ruby/command-t/Makefile
    chdir=~/.vim/bundle/command-t/ruby/command-t

- name: Compiling Command-T
  command:
    make
    creates=~/.vim/bundle/command-t/ruby/command-t/ext.bundle
    chdir=~/.vim/bundle/command-t/ruby/command-t
